--- luci-app-upnp/Makefile
+++ luci-app-upnp/Makefile
@@ -7,7 +7,6 @@
 include $(TOPDIR)/rules.mk
 
 LUCI_TITLE:=Universal Plug & Play configuration module
-LUCI_DEPENDS:=+miniupnpd
 
 include $(TOPDIR)/feeds/luci/luci.mk
 
