#!/bin/sh /etc/rc.common

[[ -f "/bin/coremark" && ! -f "/etc/bench.log" && "$(uci -q get wizard.default.coremark)" == '1' ]] && {
(
	sleep 5
	while :; do
 		[ -f /var/lock/opkg.lock ] || {
			/sbin/coremark
			break;
		}
		sleep 1
	done
) &
}
