
include $(TOPDIR)/rules.mk

LUCI_TITLE:=ua2f for luci
LUCI_DEPENDS:=+ua2f
LUCI_PKGARCH:=all
PKG_VERSION:=5.2
PKG_RELEASE:=4

include $(TOPDIR)/feeds/luci/luci.mk
# call BuildPackage - OpenWrt buildroot signature
