listen_addrs_ipv6 = ["::1"]
listen_port = 5335
prometheus_listen_addr = "[::]:9000"

[[zones]]
zone = "lan"
zone_type = "Primary"

[zones.stores]
type = "sqlite"
zone_path = "/etc/hickory-dns/lan.zone"
journal_path = "/var/lib/hickory-dns/lan.jrnl"
allow_update = true

[[zones.stores.tsig_keys]]
name = "update-key."
key_file = "/etc/hickory-dns/update.key"
algorithm = "hmac-sha256"
fudge = 300

[[zones]]
zone = "."
zone_type = "External"

[[zones.stores]]
type = "forward"
options = { edns0 = true, ip_strategy = "Ipv6AndIpv4", cache_size = 0, use_hosts_file = "Never", num_concurrent_reqs = 1, server_ordering_strategy = "RoundRobin" }

[[zones.stores.name_servers]]
ip = "2400:3200:baba::1"
trust_negative_responses = true
connections = [
    { protocol = { type = "quic", server_name = "dns.alidns.com" } },
    { protocol = { type = "h3", server_name = "dns.alidns.com", path = "/dns-query", disable_grease = false } }
]

[[zones.stores.name_servers]]
ip = "2400:3200::1"
trust_negative_responses = true
connections = [
    { protocol = { type = "quic", server_name = "dns.alidns.com" } },
    { protocol = { type = "h3", server_name = "dns.alidns.com", path = "/dns-query", disable_grease = false } }
]
