include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI app for celled
LUCI_DEPENDS:=+cellled +luci-compat
PKG_LICENSE:=GPLv3
PKG_MAINTAINER:=Konstantine Shevlakov <shevlakov@132lan.ru>

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature

