--- wifidog-wiwiz/Makefile
+++ wifidog-wiwiz/Makefile
@@ -21,7 +21,7 @@ define Package/wifidog-wiwiz
   SUBMENU:=Portal
   SECTION:=net
   CATEGORY:=Wiwiz/PinPinWiFi
-  DEPENDS:=+iptables-mod-extra +iptables-mod-ipopt +iptables-mod-nat-extra +libpthread +curl
+  DEPENDS:=+luci-app-eqos +dcc2-wiwiz-nossl +iptables-mod-extra +iptables-mod-ipopt +iptables-mod-nat-extra +libpthread +curl
   TITLE:=wifidog-wiwiz
   URL:=http://www.wiwiz.com
   MENU:=1
