

include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-xunyou
LUCI_DEPENDS:=xunyou

LUCI_TITLE:=LuCI support for xunyou
LUCI_PKGARCH:=all

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature


