#!/bin/sh /etc/rc.common

START=99
STOP=15
USE_PROCD=1

BIN_PATH="/usr/share/insomclash/insomclash"

start_service() {
    procd_open_instance insomclash
    procd_set_param command "$BIN_PATH" start
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}

stop_service() {
    procd_set_param term_timeout 15
    "$BIN_PATH" stop
    sleep 2
}

restart() {
    procd_set_param term_timeout 15
    stop
    sleep 2
    start
}

service_triggers() {
    procd_add_reload_trigger "insomclash"
}