--- luci-app-neko/Makefile
+++ luci-app-neko/Makefile
@@ -15,7 +15,7 @@ define Package/$(PKG_NAME)
 	SUBMENU:=3. Applications
 	TITLE:=LuCI support for mihomo
 	PKGARCH:=all
-	DEPENDS:=+kmod-tun +bash +curl +jq +mihomo
+	DEPENDS:=+kmod-tun +bash +curl +jq +mihomo +php8-fastcgi
 endef
 
 define Package/$(PKG_NAME)/description
