--- miniupnpd/Makefile
+++ miniupnpd/Makefile
@@ -8,8 +8,8 @@
 include $(TOPDIR)/rules.mk
 
 PKG_NAME:=miniupnpd
-PKG_VERSION:=miniupnpd_2_3_10
-PKG_RELEASE:=21
+PKG_VERSION:=2.3.10
+PKG_RELEASE:=22
 
 PKG_SOURCE_URL:=https://github.com/miniupnp/miniupnp/releases/download/miniupnpd_$(subst .,_,$(PKG_VERSION))
 PKG_SOURCE:=$(PKG_NAME)-$(PKG_VERSION).tar.gz
