

include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-nextcloud

LUCI_TITLE:=LuCI support for nextcloud
LUCI_PKGARCH:=all
LUCI_DEPENDS:=+docker +luci-lib-iform

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature


