--- luci-app-aria2/Makefile
+++ luci-app-aria2/Makefile
@@ -7,7 +7,7 @@
 include $(TOPDIR)/rules.mk
 
 LUCI_TITLE:=LuCI Support for Aria2
-LUCI_DEPENDS:=+luci-base +aria2
+LUCI_DEPENDS:=+luci-base +aria2 +ariang
 
 PKG_MAINTAINER:=Xingwang Liao <kuoruan@gmail.com>
 PKG_LICENSE:=MIT
