name: New version check
on:
  workflow_dispatch:
  schedule:
  - cron: 0 16 * * 5
  push:
    branches:
      - master

jobs:
  check:
    name: Check new version
    runs-on: ubuntu-latest
    permissions:
      contents: write  # To push a branch
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: EkkoG/openwrt-packages-version-checker@main
        env:
          COMMIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: fastfetch-cli/fastfetch
          BRANCH: master
          SOURCE_URL: https://codeload.github.com/fastfetch-cli/fastfetch/tar.gz/refs/tags/{{version}}?
          
