#!/bin/sh /etc/rc.common

START=99
STOP=15
USE_PROCD=1

BIN_PATH="/usr/share/insomclash/insomclash"
CONFIG_FILE="/etc/insomclash/app.yaml"

start_service() {
    procd_open_instance insomclash
    procd_set_param command "$BIN_PATH" -c "$CONFIG_FILE"
    procd_set_param term_timeout 15 
    procd_set_param stdout 1
    procd_set_param stderr 1
    
    procd_set_param respawn
    procd_close_instance
}

service_triggers() {
    procd_add_reload_trigger "insomclash"
}