--- luci-app-homeassistant/Makefile
+++ luci-app-homeassistant/Makefile
@@ -7,7 +7,7 @@ PKG_RELEASE:=
 
 LUCI_TITLE:=LuCI support for homeassistant
 LUCI_PKGARCH:=all
-LUCI_DEPENDS:=+docker +luci-lib-taskd
+LUCI_DEPENDS:=@(aarch64||arm||x86_64) +luci-app-dockerman +luci-lib-taskd
 
 define Package/luci-app-homeassistant/conffiles
 /etc/config/homeassistant
