#!/bin/sh /etc/rc.common

USE_PROCD=1
START=19
STOP=50

PROG=/usr/bin/ipv6-neigh

start_service() {
    procd_open_instance ipv6-neigh
    # 默认: IPv4 仅私网；IPv6 允许公网(GUA)
    procd_set_param command $PROG --private-subnet-v4 -d "[::1]:53" -z lan
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_set_param respawn "${respawn_threshold:-3600}" "${respawn_timeout:-5}" "${respawn_retry:-5}"
    procd_close_instance ipv6-neigh
}
