#!/bin/sh /etc/rc.common

USE_PROCD=1
START=19
STOP=50

PROG=/usr/bin/ipv6-neigh

start_service() {
    procd_open_instance ipv6-neigh
    procd_set_param command $PROG -p -d "[::1]:5335" -z lan
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_set_param respawn "${respawn_threshold:-3600}" "${respawn_timeout:-5}" "${respawn_retry:-5}"
    procd_close_instance ipv6-neigh
}

service_triggers() {
    procd_add_reload_trigger "dhcp" "network"
}
