include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI support for syncthing
LUCI_DEPENDS:=+syncthing
LUCI_PKGARCH:=all
PKG_RELEASE:=12

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature

