# Copyright (C) 2020 Gyj1109
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI support for syncthing
LUCI_DEPENDS:=+syncthing
LUCI_PKGARCH:=all
PKG_VERSION:=1.0
PKG_RELEASE:=16

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
