--- luci-app-ddns/Makefile
+++ luci-app-ddns/Makefile
@@ -12,7 +12,7 @@ PKG_LICENSE:=Apache-2.0
 PKG_MAINTAINER:=Ansuel Smith <ansuelsmth@gmail.com>
 
 LUCI_TITLE:=LuCI Support for Dynamic DNS Client (ddns-scripts)
-LUCI_DEPENDS:=+luci-mod-admin-full +luci-lua-runtime +ddns-scripts
+LUCI_DEPENDS:=+luci-mod-admin-full +luci-lua-runtime +ddns-scripts +ddns-scripts-aliyun +ddns-scripts-dnspod +ddns-scripts-cloudflare
 LUCI_PKGARCH:=all
 
 include ../../luci.mk
