--- luci-app-unblockneteasemusic/Makefile
+++ luci-app-unblockneteasemusic/Makefile
@@ -5,7 +5,7 @@
 include $(TOPDIR)/rules.mk
 
 LUCI_TITLE:=LuCI support for UnblockNeteaseMusic (JavaScript)
-LUCI_DEPENDS:=+dnsmasq-full +node \
+LUCI_DEPENDS:=+dnsmasq-full +node +UnblockNeteaseMusic \
 	@(PACKAGE_libustream-mbedtls||PACKAGE_libustream-openssl||PACKAGE_libustream-wolfssl)
 LUCI_PKGARCH:=all
 
